export const GET_MOVIES_START="GET_MOVIES_START"
export const GET_MOVIES_SUCCESS="GET_MOVIES_SUCCESS"
export const GET_MOVIES_FAILED="GET_MOVIES_FAILED"

export const GET_MOVIES_BY_ID_START="GET_MOVIES_BY_ID_START"
export const GET_MOVIES_BY_ID_SUCCESS="GET_MOVIES_BY_ID_SUCCESS"
export const GET_MOVIES_BY_ID_FAILED="GET_MOVIES_BY_ID_FAILED"